### ISSUE TITLE
为什么我引用字体图标是就报错。。。

### ISSUE THREAD

**Issue by luojinghui** [boring2/react-sample-gallery#1]
client?8a21:48 ./~/font-awesome/fonts/fontawesome-webfont.eot?v=4.6.3
Module parse failed: /Users/luojinghui/projects/react/gallery-by-react/node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.6.3 Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/Users/luojinghui/projects/react/gallery-by-react/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/luojinghui/projects/react/gallery-by-react/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/luojinghui/projects/react/gallery-by-react/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/luojinghui/projects/react/gallery-by-react/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/luojinghui/projects/react/gallery-by-react/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/luojinghui/projects/react/gallery-by-react/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/luojinghui/projects/react/gallery-by-react/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/luojinghui/projects/react/gallery-by-react/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/luojinghui/projects/react/gallery-by-react/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/luojinghui/projects/react/gallery-by-react/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/css-loader!./~/autoprefixer-loader?{browsers: ["last 2 version"]}!./~/font-awesome/css/font-awesome.css 6:304-355

这些是错误信息，查了好久都没有解决，帮忙看看谢谢。

**Comment by boring2** [comment]
在webpack的配置文件中加了
{
    test: /.(png|jpg|gif|woff|woff2|eot|svg|ttf)$/,
    loader: 'url-loader?limit=8192'
},
了吗?

**Comment by luojinghui** [comment]
哎，本来想引用font-awesome的字体图标库，老报错，你说的那个也引了，还是不行，然后就换回视频里面引用的字体，就好了，就是想尝试一下项目里面都是引font-awesome的图标。

**Comment by boring2** [comment]
如果你真的要引用font-awesome的话 把它的css部分
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.6.3');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.6.3') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.6.3') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.6.3') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.6.3') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}

改成如下

@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot');
  src: url('../fonts/fontawesome-webfont.eot') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2') format('woff2'), url('../fonts/fontawesome-webfont.woff') format('woff'), url('../fonts/fontawesome-webfont.ttf') format('truetype'), url('../fonts/fontawesome-webfont.svg') format('svg');
  font-weight: normal;
  font-style: normal;
}

因为你带了?v=4.6.3这些后缀 loader无法识别.
